name: messenger
services:
  db:
    image: postgres:latest
    container_name: messenger-db
    restart: always
    environment:
      POSTGRES_DB: messengerDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: whyNot_enot17
      TZ: Europe/Kyiv
    ports:
      - "5433:5432"
    volumes:
      - messenger_db_data:/var/lib/postgresql
    networks:
      - messenger-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d messengerDB"]
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: messenger:latest
    container_name: messenger-server
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "timeout 1s bash -c ':> /dev/tcp/localhost/8080' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      - DISPLAY=172.31.80.1:0.0
      - DB_URL=jdbc:postgresql://db:5432/messengerDB?serverTimezone=Europe/Kyiv
      - DB_USER=postgres
      - DB_PASSWORD=whyNot_enot17
      - TZ=Europe/Kyiv
    networks:
      - messenger-network

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: messenger:latest
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - DISPLAY=172.31.80.1:0.0
      - SERVER_HOST=backend
      - TZ=Europe/Kyiv
    command: ["org.messenger.messenger.client.AppLauncher"]
    networks:
      - messenger-network

volumes:
  messenger_db_data:
    name: messenger_db_data

networks:
  messenger-network:
    driver: bridge